server:
  port: 3003
  servlet.context-path: /api

app:
  storeFront.url: "http://localhost:3000"
  magento:
    api:
      user: "john.smith"
      password: "password123"
      baseUrl: "https://magento.test/"
      path: "rest/default/"
      imagePath: "pub/media/catalog/product"
